baseurl = "http://nmcapule.github.io/archcap2"
canonifyurls: true
languageCode = "en-us"
paginate = 9
title = "Yet another"
theme = "material-design"
MetaDataFormat = "toml"

[params]
description = ""
github = "nmcapule"
facebook = "tsymnoea"
linkedin = "nathaniel-capule"