baseurl = "http://nmcapule.github.io/archcap2"
languageCode = "en-us"
title = "Yet another"
canonifyurls = true

[params]
  description = "Striving to be better than an hour ago"
  author = "Nathaniel Capule"
